# -*- coding: utf-8 -*-
"""QC_LS_W2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnNHoNsWXepLebmJAmTVESrCfgdWyAGE
"""

import numpy as np

# Use a single complex dtype for numpy everywhere.
DTYPE = np.complex128

INV_SQRT2 = 1.0 / np.sqrt(2.0)
H = INV_SQRT2 * np.array([[1, 1], [1, -1]], dtype=DTYPE)

# LAMBDA_PI is the base rotation angle realized by the H/T building blocks:
# cos(LAMBDA_PI) = cos^2(pi/8) = (1 + 1/sqrt2)/2. Because LAMBDA_PI / (2 pi) is
# irrational, the multiples {k * LAMBDA_PI mod 2 pi} densely fill [0, 2 pi).
LAMBDA_PI = np.arccos((1.0 + INV_SQRT2) / 2.0)
TWO_PI = 2.0 * np.pi


class Bloch:
    """Axis-angle (Bloch) form of a 2x2 unitary G:

        G = e^{i alpha} (cos(theta/2) I - i sin(theta/2) (n . sigma))

    i.e. a global phase e^{i alpha} times a rotation by angle `theta` about the
    Bloch-sphere axis `n`. Here (n . sigma) = n_x X + n_y Y + n_z Z.
    """

    alpha: float  # global phase
    n: np.ndarray  # unit rotation axis, shape (3,): [n_x, n_y, n_z]
    theta: float  # rotation angle


def to_bloch(g: np.ndarray) -> Bloch:
    """Recover the Bloch form (alpha, n, theta) of a 2x2 unitary `g`."""
    det = np.linalg.det(g)
    alpha = np.angle(det) / 2.0
    u = g * np.exp(-1j * alpha)
    tr = np.trace(u)
    cos_half = np.clip(np.real(tr) / 2.0, -1.0, 1.0)
    theta = 2.0 * np.arccos(cos_half)
    sin_half = np.sin(theta / 2.0)

    if abs(sin_half) < 1e-10:
        n = np.array([1.0, 0.0, 0.0])
    else:
        nz = -np.imag(u[0, 0]) / sin_half
        nx = -np.imag(u[0, 1]) / sin_half
        ny = -np.real(u[0, 1]) / sin_half
        n = np.array([nx, ny, nz])
        n = n / np.linalg.norm(n)

    b = Bloch()
    b.alpha = float(alpha)
    b.n = n
    b.theta = float(theta)
    return b


# n1, n2 are two orthogonal Bloch-sphere axes (n1 . n2 == 0)
# TODO: fill in the two orthogonal rotation axes (each a length-3
# unit vector [x, y, z])
n1 = np.array([0.0, 0.0, 1.0])
n2 = np.array([1.0, 0.0, 0.0])

# frame derived from the axes (given)
# take the dot product of the Bloch axis with these
# the minus sign arises from the double cover issue
a1 = -n1
a2 = -n2
a3 = np.cross(a1, a2)


def n1n2n1_angles(b: Bloch) -> tuple[float, float, float, float]:
    """Factor the rotation part of a unitary (given as its Bloch form `b`) as
        u = e^{i global_phase} * Rn1(alpha) * Rn2(beta) * Rn1(gamma)

    where Ra(angle) is a rotation by `angle` about axis a, and {a1, a2, a3} is
    the orthonormal frame defined above. Returns (alpha, beta, gamma, global_phase).
    """
    # TODO(student): implement using the steps above.
    c = np.cos(b.theta)
    s = np.sin(b.theta)
    nx, ny, nz = b.n

    K = np.array([
        [0, -nz, ny],
        [nz, 0, -nx],
        [-ny, nx, 0]
    ])
    R = np.eye(3) + s * K + (1 - c) * (K @ K)

    F = np.column_stack((a1, a2, a3))
    R_prime = F.T @ R @ F

    beta = np.arccos(np.clip(R_prime[0, 0], -1.0, 1.0))

    if abs(np.sin(beta)) > 1e-8:
        alpha = np.arctan2(R_prime[1, 0], -R_prime[2, 0])
        gamma = np.arctan2(R_prime[0, 1], R_prime[0, 2])
    else:
        gamma = 0.0
        alpha = np.arctan2(R_prime[2, 1], R_prime[1, 1])

    def su2_mat(axis, ang):
        return np.cos(ang/2)*np.eye(2, dtype=DTYPE) - 1j*np.sin(ang/2)*np.array([
            [axis[2], axis[0] - 1j*axis[1]],
            [axis[0] + 1j*axis[1], -axis[2]]
        ])

    V = su2_mat(a1, alpha) @ su2_mat(a2, beta) @ su2_mat(a1, gamma)
    U = su2_mat(b.n, b.theta)
    G = np.exp(1j * b.alpha) * U

    phase_diff = np.trace(G @ V.conj().T) / 2.0
    global_phase = np.angle(phase_diff)

    return float(alpha), float(beta), float(gamma), float(global_phase)


def approx_angle_with_tolerance(angle: float, tolerance: float) -> int:
    """Find an integer multiple k such that
        (k * LAMBDA_PI) mod 2*pi  ~=  angle   (within `tolerance`)
    Since LAMBDA_PI / (2 pi) is irrational, such a k always exists; search
    k = 1, 2, 3, ... and return the first one whose wrapped multiple lands within
    `tolerance` of `angle` (compare both as angles in [0, 2 pi)).

    Hint:
      * wrap an angle into [0, 2 pi)
      * the angular distance between two wrapped angles a, b is
        min(|a - b|, TWO_PI - |a - b|) (so 0.01 and 2*pi - 0.01 count as close).
    """
    # TODO(student): implement using the hint above.
    wrapped = angle % TWO_PI
    if wrapped < 0:
        wrapped += TWO_PI

    k = 1
    while True:
        curr = (k * LAMBDA_PI) % TWO_PI
        dist = abs(curr - wrapped)
        if min(dist, TWO_PI - dist) <= tolerance:
            return k
        k += 1


def decompose_2x2(u: np.ndarray, tolerance: float) -> tuple[int, int, int]:
    """Approximate a 2x2 unitary `u` as a product of powers of M1 and M2:

        u  ~=  M1^k * M2^l * M1^m     (up to a global phase)

    where M1 is a rotation about axis a1 and M2 a rotation about axis a2, each by
    the base angle realized by the H/T building blocks. Returns the powers
    (k, l, m).

    Steps (combine the two functions above):

      1. Get the Bloch form of u (to_bloch), then factor its rotation into the
         three frame angles with n1n2n1_angles:
             alpha, beta, gamma, _global_phase = n1n2n1_angles(to_bloch(u))
         alpha and gamma are rotations about a1 (realized by powers of M1);
         beta is a rotation about a2 (realized by powers of M2).

      2. Convert each angle to an integer power with approx_angle_with_tolerance:
             k = approx_angle_with_tolerance(alpha, tolerance)   # power of M1
             l = approx_angle_with_tolerance(beta,  tolerance)   # power of M2
             m = approx_angle_with_tolerance(gamma, tolerance)   # power of M1
         (Mind the relationship between a target rotation angle and the base
         angle each application of M1/M2 adds.)

      3. Return (k, l, m).
    """
    # TODO(student): implement using the steps above.
    b = to_bloch(u)
    alpha, beta, gamma, _ = n1n2n1_angles(b)

    k = approx_angle_with_tolerance(alpha, tolerance)
    l = approx_angle_with_tolerance(beta, tolerance)
    m = approx_angle_with_tolerance(gamma, tolerance)

    return k, l, m